**Initialization of frameworks**

---

In [1]:
import numpy as np
import pandas as pd
import matplotlib as mp
print(np.__version__)
print(pd.__version__)

1.21.6
1.3.5


Creating List

In [2]:
List = list(range(10))
List

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Coverting list into string

In [3]:
StringList=[str(c) for c in List]
StringList

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

Creating Array

In [4]:
arr=np.random.randint(50,size=(3,3))
print(arr)
print("array ndim:", arr.ndim)
print("array shape:", arr.shape)
print("array size: ", arr.size)

[[14 41 33]
 [36 44 27]
 [39  7 31]]
array ndim: 2
array shape: (3, 3)
array size:  9


Pandas DataFrames

In [5]:
data = pd.DataFrame({'Country': ['Russia','Colombia','Chile','Equador','Nigeria'],
                    'Rank':[121,40,100,130,11]})
print(data)
print(data.describe())

    Country  Rank
0    Russia   121
1  Colombia    40
2     Chile   100
3   Equador   130
4   Nigeria    11
             Rank
count    5.000000
mean    80.400000
std     52.300096
min     11.000000
25%     40.000000
50%    100.000000
75%    121.000000
max    130.000000


In [6]:
data.insert(2,"grade",data['Rank']/10)

In [9]:
data.assign(grade=['a','b','c','d','e'])

Country  Rank grade
0    Russia   121     a
1  Colombia    40     b
2     Chile   100     c
3   Equador   130     d
4   Nigeria    11     e

In [10]:
data.drop(4,axis='rows',inplace=True)
data

Country  Rank  grade
0    Russia   121   12.1
1  Colombia    40    4.0
2     Chile   100   10.0
3   Equador   130   13.0

Pandas Series

In [11]:
data1 = pd.Series([1., -999., 2., -999., -1000., 3.])
data1

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [12]:
data1.replace([-999,-1000],np.nan,inplace=True)
data1

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [13]:
data.rename(columns={'contry':'Country'},inplace=True)
data

Country  Rank  grade
0    Russia   121   12.1
1  Colombia    40    4.0
2     Chile   100   10.0
3   Equador   130   13.0